name: CodeQL Analysis

on: 
  push: 
  pull_request: 

permissions:
  actions: read
  contents: read
  security-events: write  # Required for CodeQL to upload results

jobs: 
  analyze: 
    name: analyze-code
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Initialize CodeQL 
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, python

      - name: Perform CodeQL Analysis 
        uses: github/codeql-action/analyze@v3
