name: Python test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python  # Set working directory to 'python'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint black pytest pytest-cov

      - name: Run Black (Code Formatter)
        run: |
          black --check --diff .  # Check formatting for all files in python/

      - name: Run Pylint (Code Quality)
        run: |
          pylint . --fail-under=8  # Check all Python files and fail if score < 8

      - name: Run tests
        run: |
          pytest . --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html

