name: Python test
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: python
        run: |
          pip install pytest pytest-cov
          pytest python/tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=python/app --cov-report=xml --cov-report=html
