name: Security Scan
on:
  push:
  pull_request:


jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Trivy 
        run: |
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/download/v0.59.1/trivy_0.59.1_Linux-64bit.tar.gz 
          
          tar -zxvf trivy_0.59.1_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
      - name: Scan Docker image for vulnerabilities
        run: trivy fs .
